# Setup
title:        Xavier Garcia
tagline:      Aspiring research scientist.
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Xavier Garcia
  url:        https://www.linkedin.com/in/xgarcia238/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
